name: cargo-deny
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '17 3 * * 1'

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dtolnay/rust-toolchain@master
      - name: Run cargo deny
        run: cargo install cargo-deny && cargo deny check
