name: cargo-semver-checks
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


on:
  pull_request:
    paths: ['**/Cargo.toml']
  workflow_dispatch:
permissions:
  contents: read


jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: obi1kenobi/cargo-semver-checks-action@6b69fcf40e9b5fb17adeb57e4b6ecd020649a239 # v2
